### ISSUE TITLE
Produção do documento ERSw (entrega 1)

### ISSUE THREAD

**Issue by JoaoMBarros** [es20231/eqp2#1]
# Anexo

[Link do documento](https://docs.google.com/document/d/1RBzI1KlSb5mO2C-pwqcUjz2aadRPgPZF1cJy4HhX8vU/edit)

# Todo
- [x] introdução, descrição de requisitos e definição de atores.
- [x] protótipos das telas,
- [x] diagramas de classe.
- [x] diagramas de caso de uso.
- [x] fluxo de funcionalidades.
